apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  namespace: namespace-1
  labels:
    app: webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: web-container
        image: 10.13.129.47:80/demo/custom-nginx:v.15
        ports:
        - containerPort: 80